services:
  breezegate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ACME_EMAIL=admin@example.com
      - ACME_DOMAIN=example.com
    volumes:
      - ./certs:/etc/letsencrypt/live
      - ./logs:/var/log/breezegate
    restart: unless-stopped
