blank_issues_enabled: false
contact_links:
  - name: Community Discussions
    url: https://github.com/thetonbr/breezegate/discussions
    about: Ask questions and discuss with the community
  - name: Security Issues
    url: mailto:thetonbr@gmail.com
    about: Please report security vulnerabilities via email