name: Release Binaries

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build binaries
      run: |
        mkdir -p dist
        
        # Build for different platforms
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/breezegate-linux-amd64 ./cmd/app
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o dist/breezegate-linux-arm64 ./cmd/app
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o dist/breezegate-darwin-amd64 ./cmd/app
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o dist/breezegate-darwin-arm64 ./cmd/app
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/breezegate-windows-amd64.exe ./cmd/app
        
        # Create archives
        cd dist
        tar -czf breezegate-linux-amd64.tar.gz breezegate-linux-amd64
        tar -czf breezegate-linux-arm64.tar.gz breezegate-linux-arm64
        tar -czf breezegate-darwin-amd64.tar.gz breezegate-darwin-amd64
        tar -czf breezegate-darwin-arm64.tar.gz breezegate-darwin-arm64
        zip breezegate-windows-amd64.zip breezegate-windows-amd64.exe
    
    - name: Generate checksums
      run: |
        cd dist
        sha256sum *.tar.gz *.zip > checksums.txt
    
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.tar.gz
          dist/*.zip
          dist/checksums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Get release version
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/breezegate
        tags: |
          type=raw,value=${{ steps.get_version.outputs.version }}
          type=raw,value=latest,enable={{is_default_branch}}
          type=semver,pattern={{version}},value=${{ steps.get_version.outputs.version }}
          type=semver,pattern={{major}}.{{minor}},value=${{ steps.get_version.outputs.version }}
          type=semver,pattern={{major}},value=${{ steps.get_version.outputs.version }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64